version: '3.5'
services:

  sonarqube:
    image: sonarqube:lts-community
    restart: unless-stopped
    environment: 
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
      SONAR_TELEMETRY_ENABLE: 'false'
    volumes: 
      - ./vols/sonarqube/data:/opt/sonarqube/data
      - ./vols/sonarqube/extensions:/opt/sonarqube/extensions
      - ./vols/sonarqube/logs:/opt/sonarqube/logs
      - ./vols/sonarqube/temp:/opt/sonarqube/temp
    ports: 
      - '9000:9000'
    networks: 
      - gitlab

  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab
    restart: unless-stopped
    environment:
      # https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template
      GITLAB_OMNIBUS_CONFIG: |        
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
        gitlab_rails['gitlab_default_can_create_group'] = false
        gitlab_rails['gitlab_username_changing_enabled'] = false
        gitlab_rails['initial_root_password'] = '$GITLAB_PASSWORD'
        gitlab_rails['initial_shared_runners_registration_token'] = '$GITLAB_RUNNER_TOKEN'
        gitlab_rails['gitlab_kas_enabled'] = false
        gitlab_rails['gitlab_email_enabled'] = false
        gitlab_rails['incoming_email_enabled'] = false
        gitlab_rails['lfs_enabled'] = false
        gitlab_rails['terraform_state_enabled'] = false
        prometheus['monitor_kubernetes'] = false

    ports:
      - "8880:80"
      - "8822:22"
    volumes:
      - ./vols/gitlab/config:/etc/gitlab
      - ./vols/gitlab/data:/var/opt/gitlab
      - ./vols/gitlab/logs:/var/log/gitlab
    networks:
      - gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - ./vols/gitlab-runner/config.toml:/etc/gitlab-runner/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab

networks:
  gitlab: